import React from 'react';
import Link from 'next/link';
import { Navbar } from '@/components/ui/Navbar';
import { Footer } from '@/components/ui/Footer';
import { siteConfig } from '@/content/siteConfig';
import { EvidenceLine } from '@/components/ui/EvidenceLine';
import { ArrowUpRight, Cpu, Lock, CheckCircle2, AlertCircle, ShieldCheck, Mail, FileText, Database } from 'lucide-react';

export const metadata = {
  title: 'State-Space Compiler — Q-Psi Independent Quantum Research',
  description: 'Q-Psi State-Space Compiler research: mapping software repair search universes into candidate spaces and physical QPU circuits for quantum query advantage.',
};

export default function CompilerPage() {
  return (
    <div className="min-h-screen bg-surface text-text-primary flex flex-col font-sans">
      <Navbar />

      <main className="flex-grow pt-28 pb-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        {/* Header */}
        <div className="border-b border-border pb-8 space-y-4">
          <div className="inline-flex items-center space-x-2 px-3 py-1 bg-surface-raised border border-border rounded-full shadow-2xs">
            <span className="w-2 h-2 rounded-full bg-accent" />
            <span className="text-xs font-mono font-bold uppercase tracking-widest text-text-secondary">
              COMPILER RESEARCH &bull; REPRODUCIBLE BENCHMARK
            </span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-serif font-bold text-text-primary">
            Q-Psi State-Space Compiler
          </h1>
          <p className="text-base text-text-secondary max-w-3xl font-sans leading-relaxed">
            The Q-Psi compiler automates the extraction and translation of discrete software-repair search universes into structured candidate state spaces and physical circuits for superconducting quantum hardware.
          </p>
        </div>

        {/* Flagship Compiler Query Advantage Result */}
        <div className="scientific-card p-8 sm:p-12 space-y-6 bg-surface-raised border border-border">
          <div className="flex flex-wrap items-center justify-between border-b border-border pb-4 gap-4">
            <div className="space-y-1">
              <div className="inline-flex items-center space-x-2 px-2.5 py-0.5 rounded bg-[#16A34A]/10 text-[#15803D] border border-[#16A34A]/25 text-[11px] font-mono font-bold uppercase tracking-wider">
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>EXPERIMENT QPSI_COMPILER_GROVER_QUERY_ADVANTAGE_V1_1 &bull; AUDIT VERDICT: SUPPORTED</span>
              </div>
              <h2 className="text-2xl sm:text-3xl font-serif font-bold text-text-primary mt-1">
                Compiler-Enabled Quantum Query Advantage
              </h2>
            </div>
            <div className="text-xs font-mono text-text-muted">
              BACKEND: <strong className="text-text-primary">ibm_marrakesh (156Q)</strong>
            </div>
          </div>

          <p className="text-sm text-text-secondary font-sans leading-relaxed">
            Q-Psi executed a frozen quantum query advantage experiment on physical IBM Quantum hardware using authentic candidate spaces generated by the Q-Psi State-Space Compiler. Across 9 frozen instances from 7 language ecosystems, physical quantum execution achieved lower effective verifier queries than the classical black-box baseline across <strong>9/9 individual cases</strong> and <strong>3/3 problem sizes</strong> (N=4, N=8, N=16).
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 font-mono text-xs pt-1">
            <div className="p-4 bg-surface-subtle border border-border rounded space-y-2">
              <div className="flex justify-between items-center text-text-primary font-bold">
                <span>N = 4 (2 Qubits)</span>
                <span className="text-[#15803D]">2.43x ADVANTAGE</span>
              </div>
              <div className="text-text-secondary space-y-1">
                <div>Quantum Q_eff: <strong className="text-accent font-bold">1.030</strong></div>
                <div>Classical Expected: <strong className="text-text-primary">2.5</strong></div>
                <div>Physical Success: 97.09%</div>
              </div>
            </div>

            <div className="p-4 bg-surface-subtle border border-border rounded space-y-2">
              <div className="flex justify-between items-center text-text-primary font-bold">
                <span>N = 8 (3 Qubits)</span>
                <span className="text-[#15803D]">1.73x ADVANTAGE</span>
              </div>
              <div className="text-text-secondary space-y-1">
                <div>Quantum Q_eff: <strong className="text-accent font-bold">2.595</strong></div>
                <div>Classical Expected: <strong className="text-text-primary">4.5</strong></div>
                <div>Physical Success: 77.08%</div>
              </div>
            </div>

            <div className="p-4 bg-surface-subtle border border-border rounded space-y-2">
              <div className="flex justify-between items-center text-text-primary font-bold">
                <span>N = 16 (4 Qubits)</span>
                <span className="text-[#15803D]">1.19x ADVANTAGE</span>
              </div>
              <div className="text-text-secondary space-y-1">
                <div>Quantum Q_eff: <strong className="text-accent font-bold">7.144</strong></div>
                <div>Classical Expected: <strong className="text-text-primary">8.5</strong></div>
                <div>95% CI Upper: <strong className="text-[#15803D]">7.360 &lt; 8.5</strong></div>
              </div>
            </div>
          </div>

          {/* EvidenceLine with Fairness Correction Transparency */}
          <div className="pt-2 space-y-2">
            <EvidenceLine status="SUPPORTED" claimLabel="COMPILER QUERY ADVANTAGE SUPPORTED" />
            <div className="p-3 bg-surface-subtle border border-border rounded text-[11px] font-mono text-text-muted">
              <strong className="text-text-primary">PROTOCOL FAIRNESS TRANSPARENCY:</strong> The original protocol v1.0 was audited and corrected to v1.1 <em>before</em> physical QPU execution to remove compiler-rank side-channel bias via answer-independent permutation and an opaque verifier interface.
            </div>
          </div>

          <div className="pt-2 flex flex-wrap items-center gap-4 text-xs font-sans">
            <Link
              href="/research/compiler-grover-query-advantage"
              className="inline-flex items-center space-x-1.5 px-4 py-2 bg-accent text-white font-semibold rounded hover:bg-accent-hover transition-colors shadow-xs"
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Read Full Research Note</span>
            </Link>
            <Link
              href="/evidence"
              className="inline-flex items-center space-x-1.5 px-4 py-2 bg-surface-subtle border border-border text-text-primary font-semibold rounded hover:border-border-hover transition-colors"
            >
              <Database className="w-3.5 h-3.5 text-accent" />
              <span>View Raw Results &amp; Audit Hashes</span>
            </Link>
          </div>
        </div>

        {/* Technical Compilation Pipeline */}
        <div className="scientific-card p-8 space-y-6 bg-surface-raised border border-border">
          <h2 className="text-2xl font-serif font-bold text-text-primary">
            Mathematical Compilation &amp; Execution Pipeline
          </h2>
          <p className="text-xs text-text-secondary font-sans leading-relaxed">
            The compiler did not invent Grover&apos;s algorithm or amplitude amplification theory. The Q-Psi contribution tested whether authentic Q-Psi compiler-generated candidate state spaces could participate in a bounded physical-QPU query-advantage experiment under an opaque black-box verifier interface.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-6 gap-3 text-xs font-mono">
            <div className="p-4 bg-surface-subtle border border-border rounded space-y-1.5">
              <div className="text-accent font-bold text-[10px]">1. REPAIR PROBLEM</div>
              <p className="text-text-secondary font-sans text-[11px] leading-relaxed">
                Multi-file software bug state space from authentic repositories.
              </p>
            </div>
            <div className="p-4 bg-surface-subtle border border-border rounded space-y-1.5">
              <div className="text-accent font-bold text-[10px]">2. Q-PSI COMPILER</div>
              <p className="text-text-secondary font-sans text-[11px] leading-relaxed">
                Extracts discrete candidate subspace and structural relations.
              </p>
            </div>
            <div className="p-4 bg-surface-subtle border border-border rounded space-y-1.5">
              <div className="text-accent font-bold text-[10px]">3. CANDIDATE SPACE</div>
              <p className="text-text-secondary font-sans text-[11px] leading-relaxed">
                N=4, 8, 16 discrete candidate state universe.
              </p>
            </div>
            <div className="p-4 bg-surface-subtle border border-border rounded space-y-1.5">
              <div className="text-accent font-bold text-[10px]">4. OPAQUE VERIFIER</div>
              <p className="text-text-secondary font-sans text-[11px] leading-relaxed">
                Zero-leakage black-box evaluation contract.
              </p>
            </div>
            <div className="p-4 bg-surface-subtle border border-border rounded space-y-1.5">
              <div className="text-accent font-bold text-[10px]">5. PHYSICAL QPU</div>
              <p className="text-text-secondary font-sans text-[11px] leading-relaxed">
                IBM Quantum Heron 156Q execution (18,432 shots).
              </p>
            </div>
            <div className="p-4 bg-surface-subtle border border-border rounded space-y-1.5">
              <div className="text-accent font-bold text-[10px]">6. INDEPENDENT AUDIT</div>
              <p className="text-text-secondary font-sans text-[11px] leading-relaxed">
                Adversarial audit verifying 9/9 advantage cases.
              </p>
            </div>
          </div>

          <div className="p-4 bg-surface-subtle border border-border rounded text-xs font-mono space-y-2">
            <div className="flex flex-wrap items-center justify-between text-text-primary font-bold gap-2">
              <span>PHYSICAL QPU HARDWARE INTEROPERABILITY (Stage-6F Archive)</span>
              <span className="text-[#15803D] font-bold px-2 py-0.5 bg-[#16A34A]/10 rounded border border-[#16A34A]/25">
                INTEROPERABILITY PASS (Job da16h8ug52gs73cl8uog)
              </span>
            </div>
            <p className="text-text-secondary leading-relaxed font-sans text-xs">
              Earlier Stage-6F QUBO/Ising benchmark recovered exact classical global optimum on 100% of small instances (N &le; 10) on <code>ibm_marrakesh</code>. <strong>General runtime advantage or wall-clock speedup over classical software-repair pipelines is not claimed.</strong>
            </p>
          </div>
        </div>

        {/* Compiler External Research Access Flow */}
        <div className="scientific-card p-8 sm:p-12 space-y-8 bg-surface-raised border border-border">
          <div className="max-w-3xl space-y-3">
            <div className="flex items-center space-x-2 text-accent text-xs font-mono font-bold uppercase tracking-wider">
              <ShieldCheck className="w-4 h-4" />
              <span>RESEARCH EVALUATION ACCESS &bull; ACTIVATED</span>
            </div>
            <h2 className="text-3xl font-serif font-bold text-text-primary">
              Research Evaluation Access
            </h2>
            <p className="text-sm text-text-secondary font-sans leading-relaxed">
              Qualified researchers, academic laboratories, and quantum computing groups may request access to evaluate the Q-Psi State-Space Compiler using their own research workloads and target quantum-compute backends.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-2">
            {/* Box A: Research Evaluation Access Flow */}
            <div className="p-6 bg-surface-subtle border border-border rounded space-y-4 font-mono text-xs">
              <div className="font-bold text-text-primary uppercase tracking-wider flex items-center justify-between">
                <span>1. RESEARCH ACCESS EVALUATION FLOW</span>
                <span className="text-[#15803D] font-bold px-2 py-0.5 bg-[#16A34A]/10 rounded border border-[#16A34A]/25 text-[10px]">
                  STATUS: OPEN
                </span>
              </div>
              <p className="text-xs text-text-secondary font-sans leading-relaxed">
                External compiler evaluation is contribution-supported and manually fulfilled. Proprietary compiler source code is preserved securely outside public web repositories.
              </p>

              <div className="space-y-2 text-xs font-sans text-text-secondary">
                <div className="font-mono font-bold text-text-primary text-[11px]">STEP-BY-STEP ACCESS PROCEDURE:</div>
                <ol className="list-decimal list-inside space-y-1.5 text-xs text-text-secondary">
                  <li>Review research evaluation terms and claim boundaries.</li>
                  <li>Support the Q-Psi research program via the approved PayPal hosted link (flow: <strong>Research Access Contribution</strong>).</li>
                  <li>Email <a href={`mailto:${siteConfig.contact.email}`} className="text-accent font-semibold hover:underline">{siteConfig.contact.email}</a> with:
                    <ul className="pl-4 pt-1 space-y-0.5 text-text-muted text-[11px] list-disc list-inside">
                      <li>Name and institutional affiliation / lab</li>
                      <li>Intended research evaluation workload</li>
                      <li>Target quantum backend (simulator or QPU)</li>
                      <li>PayPal contribution reference</li>
                    </ul>
                  </li>
                  <li>Access instructions and Research Evaluation License key issued upon review.</li>
                </ol>
              </div>

              <div className="pt-2 flex flex-wrap gap-3">
                <Link
                  href="/capsule"
                  className="inline-flex items-center space-x-2 px-5 py-2.5 bg-accent text-white font-sans text-xs font-semibold rounded hover:bg-accent-hover transition-colors shadow-xs"
                >
                  <span>Open Q-Psi Research Capsule</span>
                  <ArrowUpRight className="w-3.5 h-3.5" />
                </Link>
                <a
                  href={siteConfig.funding.payPalUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center space-x-2 px-5 py-2.5 bg-surface border border-border text-text-primary font-sans text-xs font-semibold rounded hover:bg-surface-raised transition-colors"
                >
                  <span>Support Q-Psi Research</span>
                  <ArrowUpRight className="w-3.5 h-3.5" />
                </a>
              </div>

              <div className="text-[11px] font-sans text-text-muted">
                Disclosure: The contribution supports Q-Psi independent research. Evaluation access does not include source code ownership, automatic file download, or guaranteed benchmark results.
              </div>
            </div>

            {/* Box B: Commercial & Full Project Licensing */}
            <div className="p-6 bg-surface-subtle border border-border rounded space-y-4 font-mono text-xs">
              <div className="font-bold text-text-primary uppercase tracking-wider flex items-center justify-between">
                <span>2. FULL PROJECT &amp; COMMERCIAL LICENSING</span>
                <span className="text-text-muted font-bold px-2 py-0.5 bg-surface border border-border rounded text-[10px]">
                  CONTACT REQUIRED
                </span>
              </div>
              <p className="text-xs text-text-secondary font-sans leading-relaxed">
                For commercial integration, proprietary compiler licensing, enterprise state-space optimization pipelines, full project acquisition, or strategic research partnerships.
              </p>
              <ul className="text-xs font-sans text-text-muted space-y-1.5">
                <li>&bull; Enterprise compiler integration terms</li>
                <li>&bull; Custom superconducting/trapped-ion QPU backend transpilation</li>
                <li>&bull; Full project acquisition or dedicated sponsorship terms</li>
                <li>&bull; Direct correspondence with founder</li>
              </ul>
              <div className="pt-4 border-t border-border space-y-2">
                <div className="text-xs font-sans text-text-primary">
                  Inquiries: <a href={`mailto:${siteConfig.contact.email}`} className="text-accent font-semibold hover:underline">{siteConfig.contact.email}</a>
                </div>
                <div className="text-[11px] font-sans text-text-muted">
                  Note: Commercial licensing is handled via separate legal agreements and is strictly distinct from voluntary research-access contributions.
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
